# Generated by Django 3.1.5 on 2022-05-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0004_auto_20220523_1559'),
        ('produto', '0002_auto_20220523_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicial', models.DateTimeField()),
                ('dataFinal', models.DateTimeField()),
                ('percentualDesconto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PromocaoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promocao.promocao')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.servico')),
            ],
        ),
        migrations.CreateModel(
            name='PromocaoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.produto')),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='promocao.promocao')),
            ],
        ),
    ]
