# Generated by Django 3.1.5 on 2022-05-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20220523_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('raca', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('Cão', 'Cão'), ('Gato', 'Gato'), ('Roedor', 'Roedor'), ('Peixe', 'Peixe'), ('Réptil', 'Réptil'), ('Ave', 'Ave')], default='Cão', max_length=80)),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Média', 'Média'), ('Grande', 'Grande')], default='Média', max_length=10)),
                ('alergia', models.CharField(max_length=200, null=True)),
                ('descHabitosGostos', models.CharField(max_length=200, null=True)),
                ('autorizacaoUsoImagem', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.cliente')),
            ],
        ),
    ]
