# Generated by Django 3.1.5 on 2022-05-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pataz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdPontos', models.IntegerField()),
                ('qtdMinimaBrinde', models.IntegerField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.servico')),
            ],
        ),
    ]
