# Generated by Django 3.1.5 on 2022-05-23 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_pataz'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('dataAlteracao', models.DateField(blank=True, default=datetime.datetime.now)),
                ('usuarioAteracao', models.CharField(max_length=80)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servico.servico')),
            ],
        ),
    ]
