# Generated by Django 3.1.5 on 2022-05-23 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_historicoprecoservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoprecoservico',
            name='dataAlteracao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
