# Generated by Django 3.1.5 on 2022-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('fabricante', models.CharField(max_length=120, null=True)),
                ('especificacao', models.CharField(max_length=400, null=True)),
                ('precoVenda', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quantidade', models.IntegerField(null=True)),
            ],
        ),
    ]
