# Generated by Django 3.1.5 on 2022-05-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220523_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='tipoPetAtendimento',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='tipoPetAtendimento',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
